apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  db_host: bWljcm9zZXJ2aWNlcy1yZHMuY203d215cTQ2ZDUwLnVzLWVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbQ==
  db_user: YWRtaW4=
  db_password: Q2xvdWQxMjM=
